name: Deploy Portfolio

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'               # detects changes in the frontend
      - 'backend/**'                # detects changes in the backend
      - '.github/workflows/**'      # detects changes in this file to re-run the workflow

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code     # clones the repo onto the machine
        uses: actions/checkout@v4
      - name: Setup Node.js     # Install Node.js on the runner
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies  # Install dependencies as defined in package.lock.json
        run: npm ci
        working-directory: frontend
      - name: Build frontend        # Builds the frontend
        run: npm run build
        working-directory: frontend
      - name: Configure AWS Credentials     # Configures AWS credentials in CLI
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to S3      # Syncs the bucket with the new built, uploads only files that are changed
        run: aws s3 sync frontend/dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
      - name: Invalidate CloudFront cache       # Clear the cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}  --paths "/*"
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python      # Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Cache Python packages     # cache python packages to skip install everytime
        id: cache
        uses: actions/cache@v4
        with:
          path: backend/lambda/package
          key: lambda-deps-v2-${{ hashFiles('backend/lambda/requirements.txt') }}
      - name: Installing dependencies   # Install Python packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt -t package/
        working-directory: backend/lambda
      - name: Clean up unnecessary files    # Remove unnecessary packages to reduce size of .zip 
        run: |
          find package/ -name "*.dist-info" -type d -exec rm -rf {} +
          find package/ -name "__pycache__" -type d -exec rm -rf {} +
          du -sh package/
        working-directory: backend/lambda
      - name: Package Lambda    # Copy the lambda function file into package/ and zip it
        run: |
          cp handler.py package/
          cd package
          zip -r ../lambda_package.zip .
        working-directory: backend/lambda
      - name: Configure AWS Credentials     # Configures AWS credentials in CLI
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload zip to S3      # Uploads the created .zip file to s3 bucket that has the package file
        run: aws s3 cp backend/lambda/lambda_package.zip s3://${{ secrets.LAMBDA_BUCKET_NAME }}/lambda/lambda_package.zip
      - name: Update Lambda function
        run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.LAMBDA_BUCKET_NAME }} --s3-key lambda/lambda_package.zip